### ISSUE TITLE
old backend todos

### ISSUE THREAD

**Issue by bubuntoid** [bubuntoid/Ethereal#16]
#### Todo / Goals
v1 / mvp:
- [ ] DownloadMp3Async optimization 
  - Fork https://github.com/Tyrrrz/YoutubeExplode and reimplement **client.Videos.Streams.GetAsync(info)**
  add param with specific stream position and length<br>
  смысл в том, что нужно качать не целый видос, а начиная с какого нибудь position(int если seconds/frames, timespan - если в виде "00:00:00") и докачивать не оставшееся время видоса - а какой нибудь length (так же в секундах или фреймы)
- [ ] YOVPS.WebAPI auto tests
- [ ] VideoSplitterService unit tests
- [ ] StringExtensions unit tests
- [ ] TimeSpanExtensions unit tests
- [X] Add logs
- [X] dry VideoSplitterService
- [ ] db usage with processing status 
  - MariaDb / MySQL / PostgreSQL
- [X] total optimization
- [X] thumbnail for each chapter
- [X] native ffmpeg usage / own client (?)
- [X] choose bitrate quality
- [X] fluent validator
- [X] github ci/cd
